import 'package:hive/hive.dart';

part 'bookmark.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 0)
class Bookmark {
  @HiveField(0)
  final String arabicText;
  @HiveField(1)
  final String englishText;
  @HiveField(2)
  final int verseIndex;
  @HiveField(3)
  final int rukuNumber;
  @HiveField(4)
  final String date;
  @HiveField(5)
  final String title;
  @HiveField(6)
  final String iconType;

  Bookmark({
    required this.arabicText,
    required this.englishText,
    required this.verseIndex,
    required this.rukuNumber,
    required this.date,
    required this.title,
    required this.iconType,
  });
}
